const fs = require('fs');
let content = fs.readFileSync('views/Home.tsx', 'utf-8');

const oldList = '["YONDER", "LES HARDIS", "TALIS EDUCATION GROUP", "SKILINK", "BERNARD MAGREZ", "HÔTEL NOLINSKI", "LAZULI TRAVEL BUREAU", "LAZULI NIL", "YONDER", "LES HARDIS", "TALIS EDUCATION GROUP", "SKILINK", "BERNARD MAGREZ", "HÔTEL NOLINSKI", "LAZULI TRAVEL BUREAU", "LAZULI NIL", "YONDER", "LES HARDIS", "TALIS EDUCATION GROUP", "SKILINK", "BERNARD MAGREZ", "HÔTEL NOLINSKI", "LAZULI TRAVEL BUREAU", "LAZULI NIL"]';

const newList = '["YONDER", "LES HARDIS", "SUNLIFE GROUP", "TALIS EDUCATION GROUP", "SKILINK", "BERNARD MAGREZ", "HÔTEL NOLINSKI", "LAZULI TRAVEL BUREAU", "LAZULI NIL", "YONDER", "LES HARDIS", "SUNLIFE GROUP", "TALIS EDUCATION GROUP", "SKILINK", "BERNARD MAGREZ", "HÔTEL NOLINSKI", "LAZULI TRAVEL BUREAU", "LAZULI NIL", "YONDER", "LES HARDIS", "SUNLIFE GROUP", "TALIS EDUCATION GROUP", "SKILINK", "BERNARD MAGREZ", "HÔTEL NOLINSKI", "LAZULI TRAVEL BUREAU", "LAZULI NIL"]';

content = content.replace(oldList, newList);
fs.writeFileSync('views/Home.tsx', content);
console.log("Patched views/Home.tsx");
